### ISSUE TITLE
Рекомендация, совет:

### ISSUE THREAD

**Issue by Muxamedin** [tanasovich/hillel-python-intro#2]
https://github.com/tanasovich/hillel-python-intro/blob/8f2579bf98d68a43e7bd7325a0dc217df009ad61/lesson4/find_automorphic_numbers.py#L3
В параметрах функцый не рекомендовано использовать пробелы вокруг операторов 
вместо n + 1  записываем n+1

**Comment by tanasovich** [comment]
Исправлено. В следующие разы буду учитывать этот момент.
