### ISSUE TITLE
Не обрабатывается ввод строки - приложение падает 

### ISSUE THREAD

**Issue by Muxamedin** [tanasovich/hillel-python-intro#4]
https://github.com/tanasovich/hillel-python-intro/blob/dc7d02af80ec521f741927d0272c232af89d965b/lesson5/palindrome_pyramid.py#L1
Не обрабатывается ввод строки - приложение падает 
![image](https://user-images.githubusercontent.com/4419752/128250774-76084bf0-55c3-43ab-8bc6-13daeaa70216.png)

**Comment by tanasovich** [comment]
В скрипт добавлена проверка строки на соответствие числовому формату. В случае не соответствия, печатается сообщение об ошибке и завершается работа приложения.
