### ISSUE TITLE
cколько чисел содержится одновременно как в первом списке, так и во втором?

### ISSUE THREAD

**Issue by Muxamedin** [tanasovich/hillel-python-intro#5]
https://github.com/tanasovich/hillel-python-intro/blob/bb4f0b392b5eef58f66f4be435446a9715546c46/lesson7/count_unique_numbers_from_lists.py#L5

2. Даны два списка чисел. Посчитайте, сколько чисел содержится одновременно как в первом списке, так и во втором.

    - Примечание. Эту задачу на python можно решить в одну строчку.

**Comment by tanasovich** [comment]
Поменял оператор симметричной разности на оператор пересечения.
https://github.com/tanasovich/hillel-python-intro/blob/main/lesson7/count_common_numbers_from_lists.py
